### ISSUE TITLE
Server Crash 1.19.2 0.5.3 baublemounts

### ISSUE THREAD

**Issue by elifian** [ShadowKing21228/Bauble-Mounts#4]
I put on an empty mount bauble in the "curious slot" and after after 5-10 seconds the server crashes.
[baublemounts.log](https://github.com/user-attachments/files/17646015/baublemounts.log)

```log
[06Nov2024 15:03:38.235] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "net.minecraft.nbt.CompoundTag.m_128469_(String)" because the return value of "net.minecraft.world.item.ItemStack.m_41783_()" is null
	Index: 9
	Listeners:
		0: HIGHEST
		1: ASM: com.aizistral.enigmaticlegacy.handlers.EnigmaticEventHandler@5bc20103 onProbableDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
		2: ASM: com.aizistral.enigmaticlegacy.handlers.EnigmaticEventHandler@5bc20103 onLivingDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
		3: ASM: class twilightforest.events.CharmEvents applyDeathItems(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
		4: HIGH
		5: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
		6: NORMAL
		7: ASM: croissantnova.sanitydim.event.EventHandler@3cefa8af onLivingDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
		8: ASM: class net.tr.mc.unusualmemeshoes.procedures.CatgirlHealProcedure onEntityDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
		9: ASM: net.shadowking21.baublemounts.events.Events@4fa45bd2 onMountDead(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
		10: ASM: class com.hollingsworth.arsnouveau.common.event.PerkEvents totemEvent(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
		11: ASM: class com.hollingsworth.arsnouveau.common.block.tile.VitalicSourcelinkTile livingDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
		12: ASM: class io.redspace.ironsspellbooks.player.ServerPlayerEvents onLivingDeathEvent(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
		13: ASM: com.stal111.forbidden_arcanus.common.event.DeathEvents@3f3f4348 onLivingDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
		14: ASM: vazkii.quark.content.building.module.VariantChestsModule@5d61c11c onDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
		15: ASM: vazkii.quark.content.tweaks.module.SlimesToMagmaCubesModule@5dd2e5bc onDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
		16: ASM: air onLivingDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
		17: net.minecraftforge.eventbus.EventBus$$Lambda/0x0000000027a8f438@59ddf49a
		18: ASM: com.mrcrayfish.backpacked.common.backpack.EndCrystalBackpack@239fb58a onKillLivingEntity(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
		19: LOW
		20: ASM: com.aizistral.enigmaticlegacy.handlers.EnigmaticEventHandler@5bc20103 onDeathLow(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
		21: LOWEST
		22: ASM: com.aizistral.enigmaticlegacy.handlers.EnigmaticEventHandler@5bc20103 onConfirmedDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
		23: ASM: vazkii.quark.content.tools.module.AmbientDiscsModule@5bdbd8aa onMobDeath(Lnet/minecraftforge/event/entity/living/LivingDeathEvent;)V
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.CompoundTag.m_128469_(String)" because the return value of "net.minecraft.world.item.ItemStack.m_41783_()" is null
	at TRANSFORMER/baublemounts@0.5.3-1.19.2/net.shadowking21.baublemounts.utils.Utils.lambda$isMountBaubleEqualOnPlayer$2(Utils.java:58)
	at TRANSFORMER/forge@43.4.0/net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150)
	at TRANSFORMER/baublemounts@0.5.3-1.19.2/net.shadowking21.baublemounts.utils.Utils.isMountBaubleEqualOnPlayer(Utils.java:53)
	at TRANSFORMER/baublemounts@0.5.3-1.19.2/net.shadowking21.baublemounts.events.Events.onMountDead(Events.java:33)
	at TRANSFORMER/baublemounts@0.5.3-1.19.2/net.shadowking21.baublemounts.events.__Events_onMountDead_LivingDeathEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.4.0/net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:354)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.LivingEntity.m_6667_(LivingEntity.java:1277)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1155)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.Mob.m_7327_(Mob.java:1364)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.ai.goal.MeleeAttackGoal.m_6739_(MeleeAttackGoal.java:147)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.ai.goal.MeleeAttackGoal.m_8037_(MeleeAttackGoal.java:138)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.ai.goal.WrappedGoal.m_8037_(WrappedGoal.java:65)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.ai.goal.GoalSelector.m_186081_(GoalSelector.java:119)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.ai.goal.GoalSelector.m_25373_(GoalSelector.java:110)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.Mob.m_6140_(Mob.java:725)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2546)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.Mob.m_8107_(Mob.java:517)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.monster.Monster.m_8107_(Monster.java:42)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2291)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.entity.Mob.m_8119_(Mob.java:318)
	at TRANSFORMER/undergarden@0.8.3/quek.undergarden.entity.stoneborn.Stoneborn.m_8119_(Stoneborn.java:151)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:658)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.Level.m_46653_(Level.java:457)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
	at java.base/java.lang.Thread.run(Unknown Source)

[06Nov2024 15:03:38.323] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:870) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.CompoundTag.m_128469_(String)" because the return value of "net.minecraft.world.item.ItemStack.m_41783_()" is null
	at net.shadowking21.baublemounts.utils.Utils.lambda$isMountBaubleEqualOnPlayer$2(Utils.java:58) ~[baublemounts-0.5.3-1.19.2.jar%23271!/:0.5.3-1.19.2]
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:150) ~[forge-1.19.2-43.4.0-universal.jar%23432!/:?]
	at net.shadowking21.baublemounts.utils.Utils.isMountBaubleEqualOnPlayer(Utils.java:53) ~[baublemounts-0.5.3-1.19.2.jar%23271!/:0.5.3-1.19.2]
	at net.shadowking21.baublemounts.events.Events.onMountDead(Events.java:33) ~[baublemounts-0.5.3-1.19.2.jar%23271!/:0.5.3-1.19.2]
	at net.shadowking21.baublemounts.events.__Events_onMountDead_LivingDeathEvent.invoke(.dynamic) ~[baublemounts-0.5.3-1.19.2.jar%23271!/:0.5.3-1.19.2]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?]
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:354) ~[forge-1.19.2-43.4.0-universal.jar%23432!/:?]
	at net.minecraft.world.entity.LivingEntity.m_6667_(LivingEntity.java:1277) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	at net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1155) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	at net.minecraft.world.entity.Mob.m_7327_(Mob.java:1364) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.m_6739_(MeleeAttackGoal.java:147) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.m_8037_(MeleeAttackGoal.java:138) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8037_(WrappedGoal.java:65) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_186081_(GoalSelector.java:119) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_25373_(GoalSelector.java:110) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:725) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2546) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:517) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	at net.minecraft.world.entity.monster.Monster.m_8107_(Monster.java:42) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2291) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:318) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	at quek.undergarden.entity.stoneborn.Stoneborn.m_8119_(Stoneborn.java:151) ~[The_Undergarden-1.19.2-0.8.3.jar%23411!/:0.8.3]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:658) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:457) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23427!/:?]
	... 5 more
[06Nov2024 15:03:38.350] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 3c27ab89-3751-4b91-be25-f6db8c556aa2
[06Nov2024 15:03:38.351] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: C:\TEST\jtd-server-1.1.0 - Copy\.\crash-reports\crash-2024-11-06_15.03.38-server.txt
[06Nov2024 15:03:38.351] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[06Nov2024 15:03:38.351] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[06Nov2024 15:03:38.420] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: VelderTimes lost connection: Server closed
[06Nov2024 15:03:38.421] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: VelderTimes left the game
[06Nov2024 15:03:38.425] [Server thread/INFO] [com.alrex.parcool.ParCool/]: Limitation of d85ac27d-72c0-3278-a7b9-6dccefb067ee was unloaded
[06Nov2024 15:03:38.460] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[06Nov2024 15:03:38.918] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[06Nov2024 15:03:39.420] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[06Nov2024 15:03:39.422] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/dimdungeons:build_dimension
[06Nov2024 15:03:39.424] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/undergarden:undergarden
[06Nov2024 15:03:39.578] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/dimdungeons:dungeon_dimension
[06Nov2024 15:03:39.579] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/twilightforest:twilight_forest
[06Nov2024 15:03:39.580] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[06Nov2024 15:03:39.636] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (world): All chunks are saved
[06Nov2024 15:03:39.636] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[06Nov2024 15:03:39.636] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (build_dimension): All chunks are saved
[06Nov2024 15:03:39.636] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (undergarden): All chunks are saved
[06Nov2024 15:03:39.637] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (dungeon_dimension): All chunks are saved
[06Nov2024 15:03:39.637] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (twilight_forest): All chunks are saved
[06Nov2024 15:03:39.637] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[06Nov2024 15:03:39.637] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage: All dimensions are saved
[06Nov2024 15:03:39.667] [Server thread/INFO] [configured/]: Unloading server configs...
[06Nov2024 15:03:39.668] [Server thread/INFO] [configured/]: Sending config unload event for configured.developer.toml
```

**Comment by ShadowKing21228** [comment]
Fixed in 0.5.4 ver of mod
